# Generated by Django 3.0.6 on 2020-08-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_resumeeducation_resumejob_resumepersonalinfo_resumeskillset_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReserach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Research',
            },
        ),
    ]
