# Generated by Django 3.0.6 on 2020-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_resumereserach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeskillset',
            options={'verbose_name_plural': 'Skill'},
        ),
        migrations.RenameField(
            model_name='resumeeducation',
            old_name='location',
            new_name='programme',
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='current_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='real_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resumepersonalinfo',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
