# Generated by Django 3.0.6 on 2020-05-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ad'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time'], 'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Linking', 'verbose_name_plural': 'Linking'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tag'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='click_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myBlog.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='isCommend'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
